### PR TITLE
Feat/release on npm

### LINKED ISSUE #1: Release as npm Package
It would be great to see this as a package which anyone can import using a node package manager (NPM)

For example:

```
pragma solidity ^0.8.4;

import "erc4973/contracts/ERC4973.sol";

contract Badges is ERC4973 {
    constructor() ERC4973("Badges", "BADGE") {}

    function mint(uint256 quantity) external payable {
        // _safeMint's second argument now takes in a quantity, not a tokenId.
        _safeMint(msg.sender, quantity);
    }
}
```

### PR DESCRIPTION
**Pull request by TimDaub**
- Fixes #1
- @slavakurilyak would you mind taking a look to make sure I'm doing everything correctly?

### CODE REVIEW

**Comment by TimDaub** [comment]
bump @slavakurilyak

**Comment by slavakurilyak** [comment]
@TimDaub Unfortunately I don't have enough experience with NPM to assist with this

**Comment by TimDaub** [comment]
In the meantime we've released otterspace's contracts on npm too and so we should imitate what we did [there](https://github.com/otterspace-xyz/otterspace-contracts/blob/79852670cce954ec3579ec9bb45e6ff111cef55c/package.json#L5), here.

**Comment by markcutajar** [comment]
Would love it as an npm package too. Tested it out using yarn as well and after installing `@openzeppelin/contracts@4.5.0` everything compiled successfully.

**Comment by TimDaub** [comment]
v0.3.0 is now available on npm. Let me know in case I shall publish other older versions too. https://www.npmjs.com/package/erc4973

**Pull request merged**
