### PR TITLE
Drop local ERC165 implementation, use OZ

### PR DESCRIPTION
**Pull request by h0tw4t3r**
Implementations are the same thus it makes no sense to hold another in the repository

### CODE REVIEW

**Review by TimDaub — CHANGES_REQUESTED** [review]
I agree conceptually with your changeset. Let‘s use EIP165 from OZ. But I think your PR is reformatting code and so there are a lot of non-related changes included. Pls only change EIP165 to OZ, thx!

**Comment by h0tw4t3r** [comment]
> I agree conceptually with your changeset. Let‘s use EIP165 from OZ. But I think your PR is reformatting code and so there are a lot of non-related changes included. Pls only change EIP165 to OZ, thx!

Oooh sorry! It was `forge fmt` :D

**Comment by TimDaub** [comment]
> > I agree conceptually with your changeset. Let‘s use EIP165 from OZ. But I think your PR is reformatting code and so there are a lot of non-related changes included. Pls only change EIP165 to OZ, thx!
> 
> Oooh sorry! It was `forge fmt` :D

ah nice I hadn‘t used it before. feel free to open a second pr that

- applies forge fmt to all files
- fails CI if PRs or pushes to master branch don‘t comply with forge fmt

**Review by TimDaub — APPROVED** [review]
nice work thx

**Pull request merged**
